server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CLASS-SERVICE
          uri: lb://CLASS-SERVICE
          predicates:
            - Path=/class/**
          filters:
            - name: CircuitBreaker
              args:
                name: CLASS-SERVICE
                fallbackuri: forward:/classServiceFallBack
        - id: INSTITUTE-SERVICE
          uri: lb://INSTITUTE-SERVICE
          predicates:
            - Path=/institute/**
          filters:
            - name: CircuitBreaker
              args:
                name: INSTITUTE-SERVICE
                fallbackuri: forward:/instituteServiceFallBack
        - id: SUPERADMIN-SERVICE
          uri: lb://SUPERADMIN-SERVICE
          predicates:
            - Path=/superAdminService/**
          filters:
            - name: CircuitBreaker
              args:
                name: SUPERADMIN-SERVICE
                fallbackuri: forward:/superAdminServiceFallBack
        - id: FEIGN-SERVICE
          uri: lb://FEIGN-SERVICE
          predicates:
            - Path=/feign/**

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost