server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CLASS-SERVICE
          uri: lb://CLASS-SERVICE
          predicates:
            - Path=/class/**
        - id: INSTITUTE-SERVICE
          uri: lb://INSTITUTE-SERVICE
          predicates:
            - Path=/institute/**
        - id: SUPERADMIN-SERVICE
          uri: lb://SUPERADMIN-SERVICE
          predicates:
            - Path=/superAdminService/**
