application:
  title: Instaclass - SuperAdmin Service
  version: 1.0.0-SNAPSHOT

server:
  servlet:
    context-path: /superAdminService
  port: 0

spring:
  application:
    name: SUPERADMIN-SERVICE
  data:
    mongodb:
      database: mongo_instaclass
      host: localhost
      port: 27018

