application:
  title: Instaclass - Institute Service
  version: 1.0.0-SNAPSHOT

server:
  servlet:
    context-path: /institute
  port: 10180

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instaclass_db?currentSchema=schema_institute
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true