application:
  title: Instaclass - Class Service
  version: 1.0.0-SNAPSHOT

server:
  servlet:
    context-path: /class
  port: 10080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/instaclass?currentSchema=schema_class
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true