application:
  title: Instaclass - Class Service
  version: 1.0.0-SNAPSHOT

server:
  servlet:
    context-path: /class
  port: 0

spring:
  application:
    name: CLASS-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/instaclass?currentSchema=schema_class
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: secretkey123
