application:
  title: Instaclass - institute Service
  version: 1.0.0-SNAPSHOT

server:
  servlet:
    context-path: /institute
  port: 0

spring:
  application:
    name: INSTITUTE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/instaclass_db?currentSchema=schema_institute
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: localhost